# Generated by Django 3.2.22 on 2023-10-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_ejercicio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveBigIntegerField()),
                ('dificultad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenamientoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.PositiveIntegerField()),
                ('dificultad', models.CharField(max_length=20)),
                ('entrenamientos', models.ManyToManyField(through='fitness.EntrenamientoPlan', to='fitness.Entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoPlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.PositiveIntegerField()),
                ('plan_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.planentrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.ejercicio')),
                ('rutina_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.rutinadiaria')),
            ],
        ),
        migrations.AddField(
            model_name='rutinadiaria',
            name='ejercicios',
            field=models.ManyToManyField(through='fitness.RutinaEjercicio', to='fitness.Ejercicio'),
        ),
        migrations.AddField(
            model_name='rutinadiaria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario'),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario'),
        ),
        migrations.CreateModel(
            name='Perfil_de_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveBigIntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('foto_perfil', models.ImageField(upload_to='imagenes/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='entrenamientoplan',
            name='plan_entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.planentrenamiento'),
        ),
        migrations.CreateModel(
            name='EntrenamientoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_utilizado', models.FloatField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.ejercicio')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.entrenamiento')),
            ],
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='ejercicios',
            field=models.ManyToManyField(through='fitness.EntrenamientoEjercicio', to='fitness.Ejercicio'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='usuarios',
            field=models.ManyToManyField(through='fitness.HistorialEjercicio', to='fitness.Usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.entrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('grupo_muscular_principal', models.CharField(max_length=50)),
                ('ejercicios', models.ManyToManyField(to='fitness.Ejercicio')),
            ],
        ),
    ]
